apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-tool
  namespace: default
  labels:
    app: debug-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-tool
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debug-tool
    spec:
      restartPolicy: Always
      containers:
      - name: debug-tool
        image: winds6206/debug-tool:3.10
        stdin: true
        tty: true
        env:
          - name: TZ
            value: Asia/Taipei
